export {
  getTrending,
  getTrendingMovies,
  getPopularMovies,
  getTopRatedMovies,
  getNowPlayingMovies,
  getUpcomingMovies,
  getMovieById,
  getSimilarMovies,
  getMovieRecommendations,
  searchMovies,
  getMovieGenres,
  getMoviesByGenre,
  getMovieCast,
  getMovieVideos,
  getMovieReviews,
  getImageUrl,
  getAwardWinners,
  getDocumentaries,
  getFamilyMovies,
  getNewHotMovies,
  fetcher,
} from "../../api";

export type {
  Movie,
  TvShow,
  Genre,
  CastMember,
  CrewMember,
  Video,
  Review,
  Season,
  ApiResponse,
} from "../../api";
